FROM python:3.11-alpine

WORKDIR /app

# Install build dependencies for compiling some packages
RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev

# Upgrade pip
RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY app.py .

EXPOSE {{ backend_port }}

CMD ["python", "app.py"]
